name: Add to Project

on:
  pull_request_target:
  issues:
    types:
      - opened
      - reopened
      

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - name: Verify Token Presence
        run: |
          if [ -z "${{ secrets.PROJECTS_TOKEN }}" ]; then
            echo "PROJECTS_TOKEN is not set or empty!"
            exit 1
          else
            echo "PROJECTS_TOKEN is set!"
          fi
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Shanky-987/projects/1
          github-token: ${{ secrets.PROJECTS_TOKEN }}
